server {
    listen 80;

    location /login-with-token {
        default_type text/html;
        return 200 '
<!DOCTYPE html>
<html>
<head><title>SSO Login</title></head>
<body>
<script>
  // Get token from URL hash (#token=XYZ)
  const token = window.location.hash.split("=")[1];

  if (token) {
    // Store token (optional)
    localStorage.setItem("token", token);

    const hostName = window.location.hostname;
    // Redirect to OpenWebUI
    window.location.replace("http://" + hostName + ":3000");
  } else {
    document.body.innerText = "No token found";
  }
</script>
</body>
</html>';
    }


    location /logout-remove-token {
        default_type text/html;
        return 200 '
<!DOCTYPE html>
<html>
<head><title>SSO Logout</title></head>
<body>
<script>

  localStorage.removeItem("token");

  const hostName = window.location.hostname;

  window.location.replace("http://" + hostName + ":3000/login");

</script>
</body>
</html>';
    }

    location / {
        proxy_pass http://host.docker.internal:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}